config/routes.rb
Rails.application.routes.draw do

  resources :students
  resources :posts
  devise_for :usuarios
  get 'welcome/index'
  get 'welcome/quienes_somos'
  get 'welcome/contacto'
  get 'welcome/carreras'
  get 'welcome/servicios'
  post 'welcome/correo'

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, :description , presence: true
end

app/models/student.rb
class Student < ActiveRecord::Base
	validates :control, :nombre, :appelidos, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { :with => VALID_EMAIL_REGEX , message: "El formato del correo es invalido" }
	validates :telefono, :celular, numericality: { only_integer: true }
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_usuario!, except: [:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @title = "Inicio | UDP"
    @posts = Post.order('updated_at DESC').limit(6)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :picture)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @title = "Alumnos"
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @title = "Mostrar Registro"
  end

  # GET /students/new
  def new
    @title = "Nuevo Registro"
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    @title = "Editar Registro"
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Registro creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Registro actualizado.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Registro eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:control, :nombre, :appelidos, :direccion, :email, :telefono, :celular, :nacimiento, :ingreso, :activo, :pago, :carrera, :grupo)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@title = "Inicio | UDP"
  end

  def quienes_somos
  	@title = "Quienes Somos | UDP"
  end

  def carreras
  	@title = "Carreras | UDP"
  end

  def servicios
    @title = "Servicios | UDP"
  end

  def contacto
    @title = "Contacto | UDP"
  end

  def correo
  	@title = "Gracias"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_banner.haml
.container
  .row.col-md-3.col-md-offset-9.col-xs-7.col-xs-offset-5.anuncio
    .panel.panel-primary
      .panel-heading.text-center.bg-navy#boton Contáctanos
      .panel-body#oculto
        =form_tag(controller: "welcome", action: "correo", method: "post") do
          =text_field_tag "name",nil,class:"col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1 small-margin", placeholder:"Nombre"
          =email_field_tag "email",nil,class:"col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1 small-margin", placeholder:"Email"
          =number_field_tag "tel",nil,class:"col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1 small-margin", placeholder:"Teléfono"
          =submit_tag "Enviar", class:"center-block small-margin"

app/views/layouts/_carrera.haml
.container-fluid.top-margin
  .col-md-12.imagen
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3
      =image_tag "derecho.jpg"
      .mascara
        %h2 Licenciatura en Derecho
        %p Para quien muestra iniciativa, sensibilidad hacia los problemas sociales y actitud ética.
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3
      =image_tag "educacion.jpg"
      .mascara
        %h2 Licenciatura en Educación
        %p Para quien muestra interés por la investigación de temas educativos y construir un mejor futuro.
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3
      =image_tag "psicologia.jpg"
      .mascara
        %h2 Licenciatura en Psicología
        %p Te preparamos para desarrollarte profesionalmente en el campo del comportamiento humano.
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3
      =image_tag "forense.jpg"
      .mascara
        %h2 Licenciatura en Ciencias Forenses
        %p Profesional experto en el tratamiento de evidencia para lograr la máxima certeza en los juicios de responsabilidad.
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3
      =image_tag "social.jpg"
      .mascara
        %h2 Licenciatura en Trabajo Social
        %p Contamos con la licenciatura en educación, para todas las personas que tienen el don de enseñar.
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3
      =image_tag "medicina.jpg"
      .mascara
        %h2 Maestría en Medicina Legal
        %p Especialidad complementaria que apoya en el desempeño específico basado en los conocimientos médicos.
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3
      =image_tag "Preparatoria.jpg"
      .mascara
        %h2 Preparatoria en un Examen
        %p Realiza tu preparatoria en un solo examen, nosotros te asesoramos.
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3
      =image_tag "arte.jpg"
      .mascara
        %h2 Nuestros Horarios
        %p Para que no te quedes sin estudiar contamos con turno vespertino y turno sabatino. 

app/views/layouts/_footer.haml
%footer
	.col-md-12.bg-black.top-padding.top-margin
		.col-md-4.green-text.top-margin
			%h4.white-text.bottom-margin.text-center Contacto
			.row
				.col-md-2.col-md-offset-1
					=image_tag "location.png", width: 35, class: "opaco"
				.col-md-9
					%p Boulevard Ortiz Mena y Calle Sonora
					%p Parral, Chihuahua, México
			.row.top-padding
				.col-md-2.col-md-offset-1
					=image_tag "tel.png", width: 35, class: "opaco"
				.col-md-9
					%p Tel: 627 121 1645
			.row.top-padding
				.col-md-2.col-md-offset-1
					=image_tag "mail.png", width: 35, class: "opaco"
				.col-md-9
					%p hola@universidaddeparral.com
		.col-md-4.text-center.top-margin
			%h4.white-text.bottom-margin Síguenos en:
			=link_to (image_tag "facebook.png", width: 40), "http://www.facebook.com/universidaddeparral", class: "opaco"
			=link_to (image_tag "twitter.png", width: 50), "https://twitter.com/udpparral", class: "opaco"
			=link_to (image_tag "google.png", width: 40), "http://www.facebook.com/universidaddeparral", class: "opaco"
			=link_to (image_tag "youtube.png", width: 45), "http://www.facebook.com/universidaddeparral", class: "opaco"
		.col-md-4.text-center.green-text.hidden-xs.top-margin
			%h4.white-text.bottom-margin Licenciaturas
			%p Derecho
			%p Educación
			%p Psocología
			%p Trabajo Social
			%p Ciencias Forenses
			%p Maestría en Medicina Legal
		.col-md-12.text-center
			%p=link_to "By Jesco Marketing", "http://www.jescomarketing.com"
			%small @Copyright 2016

app/views/layouts/_header.haml
%header.container-fluid
	.col-sm-2.visible-sm
	.col-xs-12.logo.col-sm-8.col-md-4.center-block
		=link_to (image_tag 'logo2.png'), root_path
	.col-xs-12.col-md-6.col-md-offset-2.top-margin
		%nav.navbar.navbar-default.bg-suc
			.container-fluid
				.navbar-header
					%button{ "type" => "button", "class" => "navbar-toggle collapsed", "data-toggle" => "collapse", "data-target" => "#bs-example-navbar-collapse-1", "aria-expanded" => "false" }
						%span.sr-only Toggle navigation
						%span.icon-bar.black-text
						%span.icon-bar.black-text
						%span.icon-bar.black-text
				.collapse.navbar-collapse#bs-example-navbar-collapse-1
					%ul.nav.navbar-nav.black-text
						- if usuario_signed_in?
							%li{:class => "presentacion #{'activa' if current_page?(root_path)}"}=link_to "CMS", root_path
							%li{:class => "presentacion #{'activa' if current_page?(students_path)}"}=link_to "Sistema", students_path
							%li{:class => "presentacion #{'activa' if current_page?(edit_usuario_registration_path)}"}=link_to "Editar Perfil", edit_usuario_registration_path
							%li.presentacion=link_to "Salir", destroy_usuario_session_path, :method => :delete
						- else
							%li{:class => "presentacion #{'activa' if current_page?(root_path)}"}=link_to "Inicio", root_path
							%li{:class => "presentacion #{'activa' if current_page?(welcome_quienes_somos_path)}"}=link_to "Quienes Somos", welcome_quienes_somos_path
							%li{:class => "presentacion #{'activa' if current_page?(welcome_carreras_path)}"}=link_to "Carreras", welcome_carreras_path
							%li{:class => "presentacion #{'activa' if current_page?(welcome_servicios_path)}"}=link_to "Servicios", welcome_servicios_path
							%li{:class => "presentacion #{'activa' if current_page?(welcome_contacto_path)}"}=link_to "Contacto", welcome_contacto_path
							%li{:class => "presentacion #{'activa' if current_page?(usuario_session_path)}"}=link_to "Entrar", new_usuario_session_path
	- if usuario_signed_in?
		.col-md-10
		.col-md-2
			%h4 Usuario:
			=current_usuario.email

app/views/layouts/_nosotros.haml
.container-fluid.imagen.no-space.top-margin
  .col-md-12.imagen
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3.thumbnail
      =image_tag "foto1.JPG"
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3.thumbnail
      =image_tag "foto3.JPG"
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3.thumbnail
      =image_tag "foto6.JPG"
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3.thumbnail
      =image_tag "foto7.JPG"
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3.thumbnail.visible-lg
      =image_tag "foto4.JPG"
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3.thumbnail.visible-lg
      =image_tag "foto8.JPG"
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3.thumbnail.visible-lg
      =image_tag "foto5.JPG"
    .contenedor-img.ejemplo-1.no-space.col-xs-12.col-sm-6.col-md-3.thumbnail.visible-lg
      =image_tag "foto2.JPG"

app/views/layouts/_noticias.haml
.container
	.col-md-12.top-padding.bottom-padding.top-margin-md
		%h2.text-center.text-info Noticias Recientes
	.col-md-4.col-sm-6.border
		%h4.text-center.gray-text Apoyando la zona rural.
		.imagen.padding-sm.puntero=image_tag "social.jpg", { "data-toggle" => "modal", "data-target" => "#myModal" }
		%p.padding-sm Algunos de nuestros estudiantes, se reunieron para apoyar en zonas rurales, donde más necesitan.
		%button{ "type" => "button", "class" => "btn btn-primary btn-sm", "data-toggle" => "modal", "data-target" => "#myModal" } Leer Más
		.modal.fade#myModal{ "tabindex" => "-1", "role" => "dialog", "aria-labelledby" => "myModalLabel" }
			.modal-dialog{ "role" => "document" }
				.modal-content
					.modal-header.bg-green
						%button{ "type" => "button", "class" => "close", "data-dismiss" => "modal", "aria-label" => "Close"}
							%span{ "aria-hidden" => "true"} &times;
						%h4.text-center.white-text.bottom-padding-xs#myModalLabel Apoyando la zona rural
					.modal-body.bg-success
						.imagen.padding-sm=image_tag "social.jpg"
						%p.padding-sm Algunos de nuestros estudiantes, se reunieron para apoyar en zonas rurales, donde más necesitan. Estuvieron repartiendo cobertores para este tiempo de frio, ya que hay zonas donde la temperatura baja hasta los -10 grados centigrados. Algunos de nuestros estudiantes, se reunieron para apoyar en zonas rurales, donde más necesitan. Estuvieron repartiendo cobertores para este tiempo de frio, ya que hay zonas donde la temperatura baja hasta los -10 grados centigrados.
					.modal-footer
						%br
						%button{ "type" => "button", :class => "btn btn-primary btn-sm", "data-dismiss" => "modal"} Close
	.col-md-4.col-sm-6.border
		%h4.text-center.gray-text Apoyando la zona rural.
		.imagen.padding-sm.puntero=image_tag "educacion.jpg", { "data-toggle" => "modal", "data-target" => "#myModal1" }
		%p.padding-sm Algunos de nuestros estudiantes, se reunieron para apoyar en zonas rurales, donde más necesitan.
		%button{ "type" => "button", "class" => "btn btn-primary btn-sm", "data-toggle" => "modal", "data-target" => "#myModal1" } Leer Más
		.modal.fade#myModal1{ "tabindex" => "-1", "role" => "dialog", "aria-labelledby" => "myModalLabel" }
			.modal-dialog{ "role" => "document" }
				.modal-content
					.modal-header.bg-green
						%button{ "type" => "button", "class" => "close", "data-dismiss" => "modal", "aria-label" => "Close"}
							%span{ "aria-hidden" => "true"} &times;
						%h4.text-center.white-text.bottom-padding-xs#myModalLabel Apoyando la zona rural
					.modal-body.bg-success
						.imagen.padding-sm=image_tag "educacion.jpg"
						%p.padding-sm Algunos de nuestros estudiantes, se reunieron para apoyar en zonas rurales, donde más necesitan. Estuvieron repartiendo cobertores para este tiempo de frio, ya que hay zonas donde la temperatura baja hasta los -10 grados centigrados. Algunos de nuestros estudiantes, se reunieron para apoyar en zonas rurales, donde más necesitan. Estuvieron repartiendo cobertores para este tiempo de frio, ya que hay zonas donde la temperatura baja hasta los -10 grados centigrados.
					.modal-footer
						%br
						%button{ "type" => "button", :class => "btn btn-primary btn-sm", "data-dismiss" => "modal"} Close
	.col-md-4.col-sm-6.border
		%h4.text-center.gray-text Apoyando la zona rural.
		.imagen.padding-sm.puntero=image_tag "social.jpg", { "data-toggle" => "modal", "data-target" => "#myModal" }
		%p.padding-sm Algunos de nuestros estudiantes, se reunieron para apoyar en zonas rurales, donde más necesitan.
		%button{ "type" => "button", "class" => "btn btn-primary btn-sm", "data-toggle" => "modal", "data-target" => "#myModal" } Leer Más
		.modal.fade#myModal{ "tabindex" => "-1", "role" => "dialog", "aria-labelledby" => "myModalLabel" }
			.modal-dialog{ "role" => "document" }
				.modal-content
					.modal-header.bg-green
						%button{ "type" => "button", "class" => "close", "data-dismiss" => "modal", "aria-label" => "Close"}
							%span{ "aria-hidden" => "true"} &times;
						%h4.text-center.white-text.bottom-padding-xs#myModalLabel Apoyando la zona rural
					.modal-body.bg-success
						.imagen.padding-sm=image_tag "social.jpg"
						%p.padding-sm Algunos de nuestros estudiantes, se reunieron para apoyar en zonas rurales, donde más necesitan. Estuvieron repartiendo cobertores para este tiempo de frio, ya que hay zonas donde la temperatura baja hasta los -10 grados centigrados. Algunos de nuestros estudiantes, se reunieron para apoyar en zonas rurales, donde más necesitan. Estuvieron repartiendo cobertores para este tiempo de frio, ya que hay zonas donde la temperatura baja hasta los -10 grados centigrados.
					.modal-footer
						%br
						%button{ "type" => "button", :class => "btn btn-primary btn-sm", "data-dismiss" => "modal"} Close

app/views/layouts/_subir_imagen.haml
FOTOS = File.join Rails.root, 'public', 'photo_store'
	after_save :guardar_imagen

	def image=(file_data)
		unless file_data.blank?
			@file_data = file_data
			self.extension = file_data.original_filename.split('.').last.downcase
		end
	end

	def photo_filename
		File.join FOTOS, "#{id}.#{extension}"
	end

	def photo_path
		"/photo_store/#{id}.#{extension}"
	end

	def has_photo?
		File.exists? photo_filename
	end

	private

	def guardar_imagen
		if @file_data
			FileUtils.mkdir_p FOTOS
			File.open(photo_filename, 'wb') do |f|
				f.write(@file_data.read)
			end
			@file_data = nil
		end
	end

app/views/posts/edit.html.haml
.container
	.col-md-4.col-md-offset-4.col-sm-6.border.small-margin.padding-sm
		%h1 Editar noticia
		= render 'form'
		= link_to 'Mostrar', @post
		\|
		= link_to 'Regresar', posts_path

app/views/posts/index.html.haml
- if !usuario_signed_in?
  = render 'layouts/banner'
.slider
  %ul
    %li= image_tag "foto1.JPG"
    %li= image_tag "foto4.JPG"
    %li= image_tag "foto19.jpg"
.container-fluid.ej
  .col-md-12.top-padding.bottom-padding
    %h1.text-center.navy-text Bienvenidos a UDP
  .col-sm-6.col-lg-4.text-center.border
    %h3.black-text Carreras
    .circle.bg-gray.center-block.small-margin.padding-xs=link_to (image_tag "lic.png", width: 100), welcome_carreras_path
    %p.top-padding=link_to "Conoce nuestras Carreras", welcome_carreras_path
  .col-sm-6.col-lg-4.text-center.border
    %h3 Maestrías
    .circle.bg-gray.center-block.small-margin.padding-xs=link_to (image_tag "maestrias.png", width: 100), welcome_carreras_path
    %p.top-padding=link_to "Conoce nuestras Maestrías", welcome_carreras_path
  .col-sm-6.col-lg-4.text-center.border
    %h3 Campus
    .circle.bg-gray.center-block.small-margin.padding-xs=link_to (image_tag "campus.png", width: 100), welcome_quienes_somos_path
    %p.top-padding=link_to "Conoce nuestro Campus", welcome_quienes_somos_path
  .col-sm-6.col-lg-4.text-center.border
    %h3 Inscripciones
    .circle.bg-gray.center-block.small-margin.padding-xs=link_to (image_tag "inscripcion.png", width: 100)
    %p.top-padding=link_to "Conoce los requisitos de Inscripción"
  .col-sm-6.col-lg-4.text-center.border
    %h3 Becas
    .circle.bg-gray.center-block.small-margin.padding-xs=link_to (image_tag "becas.png", width: 100)
    %p.top-padding=link_to "Conoce nuestras Becas"
  .col-sm-6.col-lg-4.text-center.border
    %h3 Servicio Social
    .circle.bg-gray.center-block.small-margin.padding-xs=link_to (image_tag "social.png", width: 100)
    %p.top-padding=link_to "Realiza tu servicio social"
.container
  .col-md-12.top-margin-md
    %h2.text-center.navy-text Noticias Recientes
    - @posts.each do |post|
      .col-md-4.col-sm-6.border.small-margin
        %h4.text-center.blue-text= post.title
        .imagen.padding-sm.puntero{ "data-toggle" => "modal", "data-target" => "#miModal#{post.id}" }=image_tag post.picture
        %p.padding-sm= post.description[0..140] + "..."
        %button{ "type" => "button", "class" => "btn btn-primary btn-sm bg-blue", "data-toggle" => "modal", "data-target" => "#miModal#{post.id}" } Leer Más
        .modal.fade{ "id" => "miModal#{post.id}", "tabindex" => "-1", "role" => "dialog", "aria-labelledby" => "myModalLabel" }
          .modal-dialog{ "role" => "document" }
            .modal-content
              .modal-header.bg-green
                %button{ "type" => "button", "class" => "close", "data-dismiss" => "modal", "aria-label" => "Close"}
                  %span{ "aria-hidden" => "true"} &times;
                %h4.text-center.white-text.bottom-padding-xs#myModalLabel= post.title
              .modal-body.bg-success
                .imagen.padding-sm=image_tag post.picture
                %p.padding-sm= post.description
              .modal-footer
                %br
                %button{ "type" => "button", :class => "btn btn-primary btn-sm", "data-dismiss" => "modal"} Close
        - if usuario_signed_in?
          %p= link_to 'Editar', edit_post_path(post)
          %p= link_to 'Eliminar', post, :method => :delete, :data => { :confirm => 'Estás seguro?' }
  - if usuario_signed_in?
    %p.pull-right= link_to '+ Agregar Post', new_post_path
.col-md-12.top-margin-md
  %h2.text-center.navy-text Nuestras Carreras
= render 'layouts/carrera'

app/views/posts/new.html.haml
.container
	.col-md-6.col-md-offset-3.col-sm-6.border.small-margin.padding-sm
		%h1 Noticia Nueva
		= render 'form'
		= link_to 'Regresar', posts_path

app/views/posts/show.html.haml
.container
	.col-md-4.col-md-offset-4.col-sm-6.border.small-margin
		%h4.text-center.gray-text= @post.title
		.imagen.padding-sm.puntero=image_tag @post.picture
		%p.padding-sm= @post.description[0..140] + "..."
		= link_to 'Editar', edit_post_path(@post)
		\|
		= link_to 'Regresar', posts_path

app/views/students/edit.html.haml
.container.border
	.col-md-12.text-center.green-text
		%h2 Editar Alumno
	.col-md-2
	.col-md-8.top-margin-md
		= render 'form'
	.col-md-10
	.col-md-2.top-margin
		= link_to 'Mostrar', @student
		\|
		= link_to 'Regresar', students_path

app/views/students/index.html.haml
.container-fluid
  .col-md-12.text-center.green-text
    %h2 Alumnos Registrados
  %table.table.table-bordered.table-hover.text-center
    %thead
      %tr
        %th.text-center Número de Control
        %th.text-center Nombre
        %th.text-center Apellidos
        %th.text-center Email
        %th.text-center Teléfono
        %th.text-center Celular
        %th
        %th
        %th

    %tbody
      - @students.each do |student|
        %tr
          %td= link_to student.control, student
          %td= link_to student.nombre, student
          %td= student.appelidos
          %td= student.email
          %td= student.telefono
          %td= student.celular
          %td= link_to 'Mostrar', student
          %td= link_to 'Editar', edit_student_path(student)
          %td= link_to 'Eliminar', student, :method => :delete, :data => { :confirm => 'Estás seguro?' }

  %br

  = link_to 'Agregar Estudiante', new_student_path

app/views/students/new.html.haml
= render 'form'
.col-md-10
.col-md-2
	= link_to 'Regresar', students_path

app/views/students/show.html.haml
.container.text-justify.border
  %p#notice= notice
  .col-md-12.top-margin-md
    .col-md-7
      %h4
        %b Alumno:
        = @student.nombre + " " + @student.appelidos
    .col-md-2
    .col-md-3
      %h4
        %b # Control:
        = @student.control
  .col-md-12.top-margin-md
    .col-md-2
    .col-md-3
      %p
        %b Direccion:
        = @student.direccion
      %p
        %b Email:
        = @student.email
      %p
        %b Telefono:
        = @student.telefono
      %p
        %b Celular:
        = @student.celular
      %p
        %b Nacimiento:
        = @student.nacimiento
    .col-md-2
    .col-md-3
      %p
        %b Ingreso:
        = @student.ingreso
      %p
        %b Activo:
        - if @student.activo?
          Si
        - else
          No
      %p
        %b Pago:
        - if @student.pago?
          Si
        - else
          No
      %p
        %b Carrera:
        = @student.carrera
      %p
        %b Grupo:
        = @student.grupo
.col-md-10
.col-md-2.top-margin
  = link_to 'Editar', edit_student_path(@student)
  \|
  = link_to 'Regresar', students_path

app/views/welcome/correo.haml
.container
	.col-md-2
	.col-md8.padding-sm.top-margin
		%h3.blue-text Gracias por contactarnos, nos pondremos en contacto con usted a la brevedad.